version: '3'
services:
  discollama:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ['--redis-host', 'redis']
    environment:
      - DISCORD_TOKEN=DISCORD_KEY
      - OLLAMA_HOST=127.0.0.1
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama2-uncensored

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - /data
    ports:
      - 6379
